db{
    dbUrl = "jdbc:sqlserver://192.168.20.122:1433;databaseName=Amps;encrypt=true;trustServerCertificate=true"
    dbUser = "sa"
    dbPassword = "Srimanth@9"
    dbDriver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
}

amps {
  host = "192.168.20.60"   # AMPS SERVER IP (shared)
  port = 9007

  # All project topics (shared contract)
  topicTradesRaw        = "trades.raw"
  topicTradesEnriched   = "trades.enriched"
  topicTradesValidated  = "trades.validated"
  topicTradesFigurated    = "trades.figurated"
  topicTradesSettled    = "trades.settled"
}
